### ISSUE TITLE
Production ready node.js HTTP server

### ISSUE THREAD

**Issue by zone117x** [blockstack/gaia#253]
Meta ticket for the tasks required to remove an extra web server dependency (like nginx) as a requirement for running a gaia hub:

* [x] `/hub_info` should advertise the hub's maximum file size  https://github.com/blockstack/gaia/issues/161
* [x] Check content-size on gaia hub writes (in js http handler) https://github.com/blockstack/gaia/issues/187
* [x] Support SSL config in node.js https://github.com/blockstack/gaia/issues/252

**Comment by jeffdomke** [comment]
@muneebm @radicleart @radiclesociety you mentioned Gaia setup perviously, just tagging you here so you can keep up to date. This has be prioritized.

**Comment by zone117x** [comment]
This has been implemented and merged in dev branch since PR https://github.com/blockstack/gaia/pull/270 in September. 

There is a minor CORs bug, related to this feature, when running the write-endpoint node.js server without a reverse HTTP proxy, which is fixed in the soon to be merged PR https://github.com/blockstack/gaia/pull/276 

These lines, specifically: 
https://github.com/blockstack/gaia/pull/276/commits/395078027290dd01076d99365284c27cfcbfbfce#diff-e41f0e5dc3ecba29e76d994f3fcafb16R46-R60
